FROM elicocorp/odoo-china:10.0
User 0
RUN apt-get update &&\
    apt-get install -y \ 
        wget \ 
        git \ 
        openjdk-7-jre \ 
        libxrender1 \ 
        libxtst6 \ 
        python \ 
        libxi6 \
        --no-install-recommends &&\ 
    wget -P /tmp/ https://bootstrap.pypa.io/get-pip.py &&\
    python /tmp/get-pip.py &&\ 
    rm -rf /var/lib/apt-lists; rm -rf /tmp/*; apt-get purge wget -y; apt-get autoremove -y
RUN wget https://download.jetbrains.8686c.com/python/pycharm-community-2018.1.2.exe -O /tmp/pycharm.tar.gz 
ENV PYCHARM_HOME=/etc/pycharm
RUN mkdir ${PYCHARM_HOME} && tar -xzvf /tmp/pycharm.tar.gz -C ${PYCHARM_HOME} --strip=1
#ENTRYPOINT ["/etc/pycharm/bin/pycharm.sh"]
