# lxde docker image base
FROM rawevan/ubuntu:lxde
#MAINTAINER Evan <liaiwen_mail@163.com>
#
## install wine
#RUN echo -e "y\n29\n1" | apt-get update && apt-get install xorg --no-install-recommends
#RUN apt-get install -y lxde-core tightvncserver --no-install-recommends
#ENV HOME /root
#WORKDIR $HOME
CMD /etc/init.d/tightvncserver start
